apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-web-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /mnt/web
  persistentVolumeReclaimPolicy: Retain
