apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-static-web
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/docker/website"
  persistentVolumeReclaimPolicy: Retain
